service:
  httpPort: 80
  nodePort: 32015
  type: NodePort
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "mydrone-kube"
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - http: 
     paths:
     - backend:
         serviceName: mydrone-drone
         servicePort: 80
       path: /*
server:
  host: "http://35.193.162.45"
  env:
    DRONE_PROVIDER: "github"
    DRONE_OPEN: "false"
    DRONE_GITHUB: "true"
    DRONE_ADMIN: "me"
    DRONE_GITHUB_CLIENT: "6c17382e0cab1f1ca02d"
    DRONE_GITHUB_SECRET: "b2bbec2e2e19b215c79566d591fd8aa7687615d5"
